mirror:
    script:
        - apt-get -qq update && apt-get -qq install git
        - git config --global push.default simple
        - mkdir ~/.ssh
        - printf "%s\n" "${GITHUB_DEPLOY_KEY}" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        - echo "Pushing to git@github.com:${GITHUB_REPO}.git"
        - git push git@github.com:${GITHUB_REPO}.git
        - git push git@github.com:${GITHUB_REPO}.git --tags