mirror:
    script:
        - git config --global push.default simple
        - git checkout ${CI_COMMIT_REF_NAME}
        - cat ${GITHUB_DEPLOY_KEY} > ~/.ssh/id_rsa
        - git push -q git@github.com:${GITHUB_REPO}.git