mirror:
    script:
        - apt-get -qq update && apt-get -qq install git
        - git config --global push.default simple
        - git checkout ${CI_COMMIT_REF_NAME}
        - mkdir ~/.ssh
        - cat ${GITHUB_DEPLOY_KEY} > ~/.ssh/id_rsa
        - git push -q git@github.com:${GITHUB_REPO}.git